const env = {
  NODE_ENV: process.env.NODE_ENV || 'development',
  FIREBASE_EMULATOR_HOST: process.env.REACT_APP_FIREBASE_AUTH_EMULATOR_HOST || 'http://localhost:9099',
  FIREBASE_API_KEY: process.env.REACT_APP_FIREBASE_API_KEY || '',
  FIREBASE_AUTH_DOMAIN: process.env.REACT_APP_FIREBASE_AUTH_DOMAIN || '',
  FIREBASE_PROJECT_ID: process.env.REACT_APP_FIREBASE_PROJECT_ID || '',
  FIREBASE_STORAGE_BUCKET: process.env.REACT_APP_FIREBASE_STORAGE_BUCKET || '',
  FIREBASE_MESSAGING_SENDER_ID: process.env.REACT_APP_FIREBASE_MESSAGING_SENDER_ID || '',
  FIREBASE_APP_ID: process.env.REACT_APP_FIREBASE_APP_ID || '',
  FIREBASE_MEASUREMENT_ID: process.env.REACT_APP_FIREBASE_MEASUREMENT_ID || '',
  APP_NAME: process.env.REACT_APP_APP_NAME || 'Zoom Scheduler',
  SENTRY_DSN: process.env.REACT_APP_SENTRY_DSN || '',
  API_HOST: process.env.REACT_APP_API_HOST || 'http://localhost:8000',
};

export default env;
